### ISSUE TITLE
Create API key logic

### ISSUE THREAD

**Issue by Jdplays** [Jdplays/jams#82]
This will be the core logic for API keys that will be used by external sources

It will need another `yaml` file that will define all the endpoints and group them in a fassion like this:
```yaml
groups:
    user:
        read:
            get_users: routes.api_v1.private.admin.get_users
        write:
            edit_user: routes.api_v1.private.admin.edit_user
....
```

When doing this, it might be good to update the `pages.yaml` file to use these new endpoints. So replace `routes.api_v1.private.admin.get_users` with `get_users`

There will also need to be an API tokens DB which will store all the API keys and some base permissions
Then another table that links API keys to endpoints

Should probably store keys as HMAC keys for security

Then some decorators will need updated to handle api (keyed) requests, but still work for user requests

Todo:

- [x] Create new endpoints `yaml `along with its parsing and storage in the DB
- [x] Move `pages.yaml` to the new endpoints
- [x] Create API keys DB table along with linking table for endpoints
- [x] Update decorators

**A future feature will be done to allow API key creation in the front end**
